version: "3.7"
services:
  elasbit-relay1: 
    image: inputoutput/cardano-node:1.26.2
    container_name: elasbit-relay1
    ports: 
      - 12798:12798
    volumes:
      - $PWD/testnet/:/configuration
      - $PWD/relay1/:/relay1_logs
    deploy:
      replicas: 1
      placement:
        constraints:
            - node.labels.node_type==relay
    command: [
              "run",
              "--topology /configuration/testnet-topology.json",
              "--database-path /relay1_logs/db",
              "--socket-path /relay1_logs/db/node.socket",
              "--host-addr 0.0.0.0",
              "--port 3001",
              "--config /configuration/testnet-config.json" 
            ]
    restart: unless-stopped
  elasbit-relay2: 
    image: inputoutput/cardano-node:1.26.2
    container_name: elasbit-relay2
    deploy:
      replicas: 1
      placement:
        constraints:
            - node.labels.node_type==relay
    ports: 
      - 12799:12798
    volumes:
      - $PWD/testnet/:/configuration
      - $PWD/relay2:/relay2_logs
    command: [
              "run",
              "--topology /configuration/testnet-topology.json",
              "--database-path /relay2_logs/db",
              "--socket-path /relay2_logs/db/node.socket",
              "--host-addr 0.0.0.0",
              "--port 3001",
              "--config /configuration/testnet-config.json"
            ]
    restart: unless-stopped