version: "3"
services:
  elasbit-producing: # block-producing node
    image: inputoutput/cardano-node:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: elasbit-producing
    network_mode: host
    volumes:
      - ./test/:/config
    environment:
      - HOST_ADDR=0.0.0.0
      - NODE_PORT=3000
      - NODE_NAME=elasbit-block-producing
      - NODE_TOPOLOGY=127.0.0.1:3001/1
      - NODE_RELAY=False
      - CARDANO_NETWORK=testnet
      - EKG_PORT=12788
      - PROMETHEUS_PORT=12798
      - PROMETHEUS_HOST=127.0.0.1
      - POOL_PLEDGE=100000000000
      - POOL_COST=1000000000
      - POOL_MARGIN=0.05
      - CREATE_STAKEPOOL=True
      - METADATA_URL=https://gist.githubusercontent.com/abracadaniel/58dfa2cfe0f986c7f445deb151ed1b49/raw/4bb8155af7be65d7e9869f0923c7ce778c75368b/metadata.json
      - PUBLIC_RELAY_IP=PUBLIC
    command: run
    restart: unless-stopped
  elasbit-relay1: # relay node
    image: inputoutput/cardano-node:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: elasbit-relay1
    network_mode: host
    volumes:
      - ./test/:/config
    environment:
      - HOST_ADDR=0.0.0.0
      - NODE_PORT=3001
      - NODE_NAME=elasbit-relay1
      - NODE_TOPOLOGY=127.0.0.1:3000/1
      - NODE_RELAY=True
      - CARDANO_NETWORK=testnet
      - EKG_PORT=12788
      - PROMETHEUS_PORT=12798
      - PROMETHEUS_HOST=127.0.0.1
      - AUTO_TOPOLOGY=False
    command: run
    restart: unless-stopped