apiVersion: v1
kind: PersistentVolume
metadata:
  # To provide volumes for multiple nodes, this section is
  # duplicated and each one has a unique name
  name: cardano-elasbit-relay-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce # Only allow one container to use this volume
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage-relay1
  # Set the path to the folder on the node that will be mounted for this volume
  local:
    path: /home/ubuntu/cardano/relay1/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: node_role
            operator: In
            values:
              - relay1
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-relay1

apiVersion: v1
kind: PersistentVolume
metadata:
  # To provide volumes for multiple nodes, this section is
  # duplicated and each one has a unique name
  name: cardano-elasbit-relay-2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce # Only allow one container to use this volume
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage-relay2
  # Set the path to the folder on the node that will be mounted for this volume
  local:
    path: /home/ubuntu/cardano/relay2/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: node_role
            operator: In
            values:
              - relay2
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-relay2

